[project]
name = "nonebot-plugin-heweather"
version = "0.6.7"
description = "Get Heweather information and convert to pictures"
authors = [
    {name = "kexue", email = "xana278@foxmail.com"},
]
dependencies = [
    "httpx<1.0.0,>=0.18.0",
    "nonebot-plugin-htmlrender>=0.0.4.3",
    "nonebot-adapter-onebot>=2.0.0",
    "pydantic>=1.5.0",
    "nonebot2[fastapi]>=2.0.0",
]
requires-python = ">=3.8,<4.0"
license = {text = "MIT"}
readme = "README.md"

[project.group.dev.dependencies]
Pillow = "^9.1.1"
isort = "^5.10.1"
nonebug = "^0.2.1"
pytest-asyncio = "^0.20.3"

[project.group.dev.dependencies.black]
version = "^21.12b0"
allow-prereleases = true


[tool.pdm.build]
includes = []

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.isort]
profile = "black"
line_length = 88
length_sort = true
skip_gitignore = true
force_sort_within_sections = true
